[package]
name = "openmuse-office-docx"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license = "AGPL-3.0-only"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
quick-xml.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
zip.workspace = true

[dev-dependencies]
sha2.workspace = true
