display_name: DSH Office
icon: linux/packaging/assets/logo.png
group: Applications/Office
vendor: OpenMuseAI
packager: OpenMuseAI
packagerEmail: https://github.com/openmuseai/dsh-office/issues
license: AGPL-3.0
url: https://github.com/openmuseai/dsh-office

build_arch: x86_64

keywords:
  - DSH Office
  - Office
  - Document
  - Database
  - Note
  - Kanban
  - AI

generic_name: DSH Office

categories:
  - Office
  - Productivity

startup_notify: true

supportedMimeType: x-scheme-handler/appflowy-flutter

requires:
  - libnotify
  - keybinder