import { createHash } from "node:crypto";
import { planCompositionV2, validateManifestV2, type CompositionPlanV2, type HostDescriptorV2, type MusePluginManifestV2 } from "@muse/plugin-graph";

export { planCompositionV2, validateManifestV2 } from "@muse/plugin-graph";
export type { CompositionPlanV2, HostDescriptorV2, MusePluginManifestV2 } from "@muse/plugin-graph";
export { verifyArtifactV2, diffPermissionsV2 } from "@muse/plugin-security";

export interface ScaffoldOutputV2 { readonly files: Readonly<Record<string, string>>; }
export const scaffoldPluginV2 = (pluginId: string): ScaffoldOutputV2 => {
  if (!/^[a-z0-9][a-z0-9._-]*$/.test(pluginId)) throw new Error("INVALID_PLUGIN_ID");
  const manifest: MusePluginManifestV2 = {
    protocol: "muse.plugin/v2", pluginId, version: "0.1.0",
    artifacts: [{ id: "agent", digest: `sha256:${"0".repeat(64)}`, kind: "npm", entrypoint: "./dist/index.js" }],
    facets: [{ id: "agent", kind: "agent", artifact: "agent", runtimes: ["dsh-native", "remote-dsh"] }]
  };
  return { files: {
    "muse.plugin.json": `${JSON.stringify(manifest, null, 2)}\n`,
    "src/index.ts": "export const name = 'example';\nexport const apply = () => undefined;\n",
    "README.md": `# ${pluginId}\n\nGenerated by @muse/ecosystem-sdk v2.\n`
  } };
};

export const validatePluginV2 = (value: unknown): MusePluginManifestV2 => validateManifestV2(value);
export const planPluginV2 = (manifests: readonly unknown[], host: HostDescriptorV2): CompositionPlanV2 => planCompositionV2({ manifests, host });
export const packageArtifactV2 = (bytes: Uint8Array): { readonly digest: `sha256:${string}`; readonly size: number } => ({ digest: `sha256:${createHash("sha256").update(bytes).digest("hex")}`, size: bytes.byteLength });

export interface DiagnosticV2 { readonly level: "info" | "error"; readonly code: string; readonly message: string; }
export const diagnosePluginV2 = (manifest: unknown, hosts: readonly HostDescriptorV2[]): readonly DiagnosticV2[] => {
  try {
    const valid = validateManifestV2(manifest); const diagnostics: DiagnosticV2[] = [];
    for (const host of hosts) {
      const plan = planCompositionV2({ manifests: [valid], host });
      diagnostics.push({ level: plan.rejectedPlugins.length === 0 ? "info" : "error", code: plan.rejectedPlugins.length === 0 ? "HOST_COMPATIBLE" : "HOST_REJECTED", message: `${host.hostId}:${plan.digest}` });
    }
    return diagnostics;
  } catch (error) { return [{ level: "error", code: "MANIFEST_INVALID", message: error instanceof Error ? error.message : "invalid" }]; }
};

export interface PluginTckResultV2 { readonly passed: boolean; readonly plans: readonly { readonly platform: string; readonly digest: string; readonly accepted: boolean }[]; }
export const runPluginTckV2 = (manifest: unknown): PluginTckResultV2 => {
  const valid = validateManifestV2(manifest);
  const hosts: HostDescriptorV2[] = [
    { protocol: "muse.host/v2", hostId: "tck-desktop", platform: "desktop", runtimes: ["dsh-native", "flutter", "rust-host"], builtInContracts: [], allowedGrants: [] },
    { protocol: "muse.host/v2", hostId: "tck-mobile", platform: "mobile", runtimes: ["remote-dsh", "flutter", "rust-host"], builtInContracts: [], allowedGrants: [] },
    { protocol: "muse.host/v2", hostId: "tck-web", platform: "web", runtimes: ["remote-dsh", "flutter"], builtInContracts: [], allowedGrants: [] }
  ];
  const plans = hosts.map(host => { const plan = planCompositionV2({ manifests: [valid], host }); return { platform: host.platform, digest: plan.digest, accepted: plan.acceptedPlugins.includes(valid.pluginId) }; });
  return { passed: plans.every(value => value.accepted), plans };
};

export const compatibilityMatrixV2 = Object.freeze({
  muse: { current: "2.0", previous: "2.x minor" }, bridge: { wireMajor: 1, supportedMinor: "N/N-1" },
  dsh: { native: "pinned workspace release", portable: "public Tool/SystemPrompt seams" },
  contracts: { document: "2.x", table: "1.x" }, platforms: ["desktop", "mobile", "web"] as const
});
